export type Language = "en" | "de";

export const copy = {
  en: {
    brand: "neighborhood service desk",
    demoMode: "Demo mode",
    heroEyebrow: "GOOD NEIGHBORS, BETTER DAYS",
    heroLineOne: "What can we help",
    heroLineTwo: "you with today?",
    heroDescription: "Report a neighborhood issue, check an update, or find time to talk. No account needed.",
    choosePath: "CHOOSE A PATH",
    services: "Services",
    reportAction: "Report an issue",
    reportActionDescription: "Tell us what needs attention in your neighborhood.",
    trackAction: "Track a report",
    trackActionDescription: "See what is happening with a request.",
    bookAction: "Book a visit",
    bookActionDescription: "Find a short appointment with our team.",
    back: "Back",
    backHome: "Back to home",
    allDone: "ALL DONE",
    done: "Done",
    reportEyebrow: "REPORT AN ISSUE",
    reportTitle: "Something needs attention?",
    reportSubtitle: "A few details will help the team find and understand it.",
    whatHappened: "What happened?",
    closestMatch: "Pick the closest match.",
    issueType: "Issue type",
    streetlight: "Streetlight",
    road: "Road or pavement",
    waste: "Waste collection",
    other: "Other",
    where: "Where is it?",
    landmarkHint: "Street and nearest landmark",
    locationPlaceholder: "e.g. Maple Street, near number 12",
    whatNoticed: "What did you notice?",
    detailsPlaceholder: "Describe the issue in a sentence or two...",
    chooseIssueError: "Choose the type of issue first.",
    locationError: "Add a street and a nearby landmark so the team can find it.",
    detailsError: "Add a little more detail about what you noticed.",
    reviewReport: "Review report",
    reviewEyebrow: "ONE LAST LOOK",
    reviewTitle: "Check your report",
    reviewSubtitle: "Make sure these details will help us find the issue.",
    issue: "Issue",
    location: "Location",
    details: "Details",
    editDetails: "Edit details",
    sendReport: "Send report",
    reportSent: "Report sent.",
    reportSentSubtitle: "We have your report and will take a look.",
    yourReference: "YOUR REFERENCE",
    referenceHelp: "Keep this number to check the latest update. Your report is saved on this device.",
    viewReport: "View report",
    trackEyebrow: "TRACK A REPORT",
    trackTitle: "Let's find your update.",
    trackSubtitle: "Enter a reference to see the latest status.",
    reportReference: "Report reference",
    demoReference: "A demo report is ready: NS-1042",
    referenceError: "We couldn't find that reference. Try NS-1042 for the demo report.",
    findReport: "Find report",
    updateEyebrow: "REPORT UPDATE",
    updateTitle: "Here's the latest.",
    reference: "Reference",
    received: "Received",
    inProgress: "In progress",
    demoReport: "Demo report",
    justNow: "Just now",
    seedLocation: "Maple Street, near number 12",
    seedDetails: "The streetlight beside the crossing is not working.",
    reportReceived: "Report received",
    receivedDetails: "We have the details.",
    teamReview: "Team review",
    teamWorking: "The team is looking into it.",
    nextStep: "This is the next step.",
    resolved: "Resolved",
    resolutionNote: "We will update this status when complete.",
    bookEyebrow: "BOOK A VISIT",
    bookTitle: "Let's make time to talk.",
    bookSubtitle: "Choose what you need help with, then pick a time.",
    visitAbout: "What is your visit about?",
    housing: "Housing advice",
    permits: "Permits and forms",
    general: "General help",
    pickDay: "Pick a day",
    appointmentDay: "Appointment day",
    today: "Today",
    tomorrow: "Tomorrow",
    nextDay: "Next day",
    fullyBooked: "Fully booked",
    twoTimes: "2 times",
    availableTimes: "Available times",
    appointmentTime: "Appointment time",
    noTimes: "No times left today. Try another day above.",
    chooseTimeError: "Choose an available time to continue.",
    confirmVisit: "Confirm visit",
    booked: "You're booked.",
    bookedSubtitle: "Your appointment is saved on this device.",
    yourVisit: "YOUR VISIT",
    at: "at",
    footerName: "Northstar Neighborhood Service Desk",
    localDemo: "A local demo",
    resetDemo: "Reset demo",
    resetTitle: "Start fresh?",
    resetDescription: "This clears the reports and bookings you made on this device. The demo report NS-1042 will still be there.",
    keepWork: "Keep my work",
  },
  de: {
    brand: "Nachbarschaftsservice",
    demoMode: "Demomodus",
    heroEyebrow: "GUTE NACHBARSCHAFT, GUTER ALLTAG",
    heroLineOne: "Wobei können wir",
    heroLineTwo: "heute helfen?",
    heroDescription: "Melde ein Problem in deiner Nachbarschaft, prüfe den Stand einer Meldung oder vereinbare einen Termin. Ganz ohne Konto.",
    choosePath: "WÄHLE EINEN WEG",
    services: "Angebote",
    reportAction: "Problem melden",
    reportActionDescription: "Sag uns, was in deiner Nachbarschaft Aufmerksamkeit braucht.",
    trackAction: "Meldung verfolgen",
    trackActionDescription: "Sieh nach, was aus deiner Meldung geworden ist.",
    bookAction: "Termin buchen",
    bookActionDescription: "Vereinbare einen kurzen Termin mit unserem Team.",
    back: "Zurück",
    backHome: "Zur Startseite",
    allDone: "GESCHAFFT",
    done: "Fertig",
    reportEyebrow: "PROBLEM MELDEN",
    reportTitle: "Etwas braucht Aufmerksamkeit?",
    reportSubtitle: "Ein paar Angaben helfen dem Team, das Problem zu finden und zu verstehen.",
    whatHappened: "Was ist passiert?",
    closestMatch: "Wähle die passende Kategorie.",
    issueType: "Art des Problems",
    streetlight: "Straßenlaterne",
    road: "Straße oder Gehweg",
    waste: "Müllabfuhr",
    other: "Sonstiges",
    where: "Wo ist es?",
    landmarkHint: "Straße und Orientierungspunkt in der Nähe",
    locationPlaceholder: "z. B. Ahornstraße, bei Hausnummer 12",
    whatNoticed: "Was ist dir aufgefallen?",
    detailsPlaceholder: "Beschreibe das Problem in ein bis zwei Sätzen ...",
    chooseIssueError: "Wähle zuerst eine Kategorie.",
    locationError: "Nenne eine Straße und einen Orientierungspunkt, damit das Team den Ort findet.",
    detailsError: "Beschreibe etwas genauer, was dir aufgefallen ist.",
    reviewReport: "Meldung prüfen",
    reviewEyebrow: "NOCH EIN BLICK",
    reviewTitle: "Prüfe deine Meldung",
    reviewSubtitle: "Stimmen die Angaben, damit wir das Problem finden können?",
    issue: "Problem",
    location: "Ort",
    details: "Beschreibung",
    editDetails: "Angaben ändern",
    sendReport: "Meldung senden",
    reportSent: "Meldung gesendet.",
    reportSentSubtitle: "Wir haben deine Meldung erhalten und sehen sie uns an.",
    yourReference: "DEINE NUMMER",
    referenceHelp: "Mit dieser Nummer kannst du den Stand prüfen. Deine Meldung ist auf diesem Gerät gespeichert.",
    viewReport: "Meldung ansehen",
    trackEyebrow: "MELDUNG VERFOLGEN",
    trackTitle: "Hier ist der aktuelle Stand.",
    trackSubtitle: "Gib eine Vorgangsnummer ein, um den Status zu sehen.",
    reportReference: "Vorgangsnummer",
    demoReference: "Eine Demomeldung ist vorhanden: NS-1042",
    referenceError: "Diese Nummer haben wir nicht gefunden. Probiere NS-1042 für die Demomeldung.",
    findReport: "Meldung finden",
    updateEyebrow: "AKTUELLER STAND",
    updateTitle: "Das ist der Stand.",
    reference: "Vorgang",
    received: "Eingegangen",
    inProgress: "In Bearbeitung",
    demoReport: "Demomeldung",
    justNow: "Gerade eben",
    seedLocation: "Ahornstraße, bei Hausnummer 12",
    seedDetails: "Die Straßenlaterne neben dem Übergang funktioniert nicht.",
    reportReceived: "Meldung eingegangen",
    receivedDetails: "Wir haben die Angaben erhalten.",
    teamReview: "Prüfung durch das Team",
    teamWorking: "Das Team kümmert sich darum.",
    nextStep: "Das ist der nächste Schritt.",
    resolved: "Erledigt",
    resolutionNote: "Wir aktualisieren den Status, sobald das Problem behoben ist.",
    bookEyebrow: "TERMIN BUCHEN",
    bookTitle: "Wir nehmen uns Zeit.",
    bookSubtitle: "Wähle ein Thema und danach eine Uhrzeit.",
    visitAbout: "Worum geht es bei deinem Termin?",
    housing: "Wohnen und Miete",
    permits: "Anträge und Formulare",
    general: "Allgemeine Beratung",
    pickDay: "Wähle einen Tag",
    appointmentDay: "Tag des Termins",
    today: "Heute",
    tomorrow: "Morgen",
    nextDay: "Übermorgen",
    fullyBooked: "Ausgebucht",
    twoTimes: "2 Termine",
    availableTimes: "Freie Uhrzeiten",
    appointmentTime: "Uhrzeit des Termins",
    noTimes: "Heute ist nichts mehr frei. Wähle oben einen anderen Tag.",
    chooseTimeError: "Wähle eine freie Uhrzeit aus.",
    confirmVisit: "Termin bestätigen",
    booked: "Termin gebucht.",
    bookedSubtitle: "Dein Termin ist auf diesem Gerät gespeichert.",
    yourVisit: "DEIN TERMIN",
    at: "um",
    footerName: "Northstar Nachbarschaftsservice",
    localDemo: "Eine lokale Demo",
    resetDemo: "Demo zurücksetzen",
    resetTitle: "Neu anfangen?",
    resetDescription: "Dadurch werden deine Meldungen und Termine auf diesem Gerät gelöscht. Die Demomeldung NS-1042 bleibt erhalten.",
    keepWork: "Daten behalten",
  },
} as const;
